language: python

env:
  matrix:
    - CIBW_SKIP: cp34-* cp35-* cp36-* cp37-* cp38-*
    - CIBW_SKIP: cp27-* cp33-* cp36-* cp37-* cp38-*
    - CIBW_SKIP: cp27-* cp33-* cp34-* cp35-*
  global:
    CIBW_BUILD_VERBOSITY: 3

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx

script:
  - export PYTHON_EXEC_PATH=$(which python)
  - rm -rf $PYTHON_EXEC_PATH
  - ln -s $(which python3) $PYTHON_EXEC_PATH
  - python --version
  - python3 --version
  - python3 -m pip install pip setuptools -U
  - python3 -m pip install cibuildwheel==1.4.1
  - eval "buildwheel() { cibuildwheel --output-dir wheelhouse >>buildwheel.log 2>&1; }"
  - travis_wait 60 buildwheel || (tail -c 3670016 buildwheel.log && exit 1)
  - tail -c 3670016 buildwheel.log
  - ls wheelhouse
  - python3 -m pip install awscli --upgrade
  - aws s3 sync ./wheelhouse/ s3://magnitude.plasticity.ai/wheelhouse/
