language: python

env:
  global:
    CIBW_BUILD_VERBOSITY: 3

language: generic

os:
  - linux
  - osx

matrix:
  exclude:
    - os: linux

script:
  - export PYTHON_EXEC_PATH=$(which python)
  - rm -rf $PYTHON_EXEC_PATH
  - ln -s $(which python3) $PYTHON_EXEC_PATH
  - python --version
  - python3 --version
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - python3 -m pip install pip setuptools -U
  - python3 -m pip install cibuildwheel==1.4.1
  - eval "buildwheel() { cibuildwheel --output-dir wheelhouse >>buildwheel.log 2>&1; }"
  - travis_wait 60 buildwheel || (tail -c 3670016 buildwheel.log && exit 1)
  - tail -c 3670016 buildwheel.log
  - ls wheelhouse
  - python3 -m pip install awscli --upgrade
  - brew install awscli || true
  - aws s3 sync ./wheelhouse/ s3://magnitude.plasticity.ai/wheelhouse/
